version: "3.9"
services:

#  notebook:
#    container_name: notebook
#    build:
#      context: ./jupyter_notebook
#      dockerfile: Dockerfile
#    volumes:
#      - "./jupyter_notebook:/notebook"
#    ports:
#      - "8888:8888"

  db:
    container_name: db
    image: postgres:13
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ny_taxi
    volumes:
      - "./postgres/data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    networks:
      - default
      - airflow

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - "./pg_admin/data:/var/lib/pgadmin"
    ports:
      - "8081:80"

#  app:
#    container_name: app
#    build:
#      context: ./app
#      dockerfile: Dockerfile
#    volumes:
#      - "./app:/app"
#    depends_on:
#      - db

networks:
  airflow:
    external:
      name: airflow_default